"""
trinetx_docx_parser.py

Native OpenXML parser for TriNetX 'Compare Outcomes' DOCX report exports.
Handles multi-body document.xml structures produced by TriNetX export.
Extracts:
- Metadata: analysis name, cohort names, N (intro vs matching), time window
- Table 1: Demographics, Diagnosis, Medication, Laboratory (Before & After PSM)
- Table 2: Outcomes (Risk, Kaplan-Meier, Log-Rank, Hazard Ratio)
- Table S1: Appendices A, B, C (Inclusion, Exclusions, Outcomes, Covariates)
"""

import zipfile
import xml.etree.ElementTree as ET
import re
from typing import Dict, List, Any, Optional

NS = {'w': 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'}

def _cell_lines(tc: ET.Element) -> List[str]:
    """Extract text lines from a table cell, respecting <w:br/> and <w:p/> line breaks."""
    parts = []
    for elem in tc.iter():
        if elem.tag.endswith('}t'):
            parts.append(elem.text or '')
        elif elem.tag.endswith('}br') or elem.tag.endswith('}p'):
            parts.append('\n')
    lines = [line.strip() for line in ''.join(parts).split('\n') if line.strip()]
    return lines

def _body_text(body: ET.Element) -> str:
    """Extract plain text from a body element."""
    lines = []
    for p in body.iter(f"{{{NS['w']}}}p"):
        t = ''.join(p.itertext()).strip()
        if t:
            lines.append(t)
    return '\n'.join(lines)

def parse_trinetx_docx(docx_path: str) -> Dict[str, Any]:
    with zipfile.ZipFile(docx_path) as z:
        xml_content = z.read('word/document.xml')
    root = ET.fromstring(xml_content)
    bodies = root.findall('.//w:body', NS)
    
    if len(bodies) < 12:
        raise ValueError(f"Expected at least 12 bodies in TriNetX DOCX, found {len(bodies)}")
        
    data: Dict[str, Any] = {
        'docx_path': docx_path,
        'analysis_name': '',
        'created_date': '',
        'intro_cohort_a': {'name': '', 'n': 0},
        'intro_cohort_b': {'name': '', 'n': 0},
        'matching_cohort_1': {'name': '', 'n_before': 0, 'n_after': 0},
        'matching_cohort_2': {'name': '', 'n_before': 0, 'n_after': 0},
        'time_window_text': '',
        'time_window_days': 0,
        'table1_sections': [],
        'table2_outcomes': [],
        'appendix_a_text': '',
        'appendix_b_text': '',
        'appendix_c_text': '',
        'codes_universe': set(),
    }

    # 1. Header and Intro (Body 0 and 1)
    b1_text = _body_text(bodies[1])
    m_analysis = re.search(r'named\s+([^,]+?),\s+generated by', b1_text)
    if m_analysis:
        data['analysis_name'] = m_analysis.group(1).strip()
    
    m_created = re.search(r'generated by the TriNetX platform on\s+([^.]+?\s+UTC)', b1_text)
    if m_created:
        data['created_date'] = m_created.group(1).strip()

    m_cohorts = re.search(r'Cohort A\s*\(([\d,]+)\s*patients\)\s*named\s+(.+?)\s+and Cohort B\s*\(([\d,]+)\s*patients\)\s*named\s+([^.\n]+)', b1_text)
    if m_cohorts:
        data['intro_cohort_a'] = {'n': int(m_cohorts.group(1).replace(',', '')), 'name': m_cohorts.group(2).strip()}
        data['intro_cohort_b'] = {'n': int(m_cohorts.group(3).replace(',', '')), 'name': m_cohorts.group(4).strip()}

    # 2. Analysis Setup / Time Window (Body 3)
    b3_text = _body_text(bodies[3])
    m_tw = re.search(r'time window that started.*?and ended\s+(\d+)\s+days after the first occurrence of the index event', b3_text, re.IGNORECASE)
    if m_tw:
        data['time_window_days'] = int(m_tw.group(1))
        data['time_window_text'] = f"{m_tw.group(1)} days"
    else:
        m_tw2 = re.search(r'ended\s+([^.\n]+?after the first occurrence of the index event)', b3_text, re.IGNORECASE)
        if m_tw2:
            data['time_window_text'] = m_tw2.group(1).strip()

    # 3. Propensity Score Matching & Table 1 Characteristics (Body 5)
    b5 = bodies[5]
    b5_tbls = b5.findall('.//w:tbl', NS)
    if not b5_tbls:
        raise ValueError("No table found in Body 5 (Propensity Score Matching)")
    tbl_psm = b5_tbls[0]
    
    psm_rows = []
    for tr in tbl_psm.findall('.//w:tr', NS):
        row_cells = [_cell_lines(tc) for tc in tr.findall('./w:tc', NS)]
        psm_rows.append(row_cells)

    # Patient counts before and after matching
    for r in psm_rows[1:5]:
        clean = [c for c in r if c]
        if len(clean) >= 3 and any('1 -' in x for x in clean[0]):
            txt_row = [' '.join(c) for c in clean]
            data['matching_cohort_1'] = {
                'name': re.sub(r'^\d+\s*-\s*', '', txt_row[0]).strip(),
                'n_before': int(txt_row[1].replace(',', '')),
                'n_after': int(txt_row[2].replace(',', '')),
            }
        elif len(clean) >= 3 and any('2 -' in x for x in clean[0]):
            txt_row = [' '.join(c) for c in clean]
            data['matching_cohort_2'] = {
                'name': re.sub(r'^\d+\s*-\s*', '', txt_row[0]).strip(),
                'n_before': int(txt_row[1].replace(',', '')),
                'n_after': int(txt_row[2].replace(',', '')),
            }

    # Find boundaries
    before_idx = -1
    after_idx = -1
    for idx, r in enumerate(psm_rows):
        row_str = ' '.join(' '.join(c) for c in r if c)
        if 'characteristics before propensity score matching' in row_str.lower():
            before_idx = idx
        elif 'characteristics after propensity score matching' in row_str.lower():
            after_idx = idx

    if before_idx == -1 or after_idx == -1:
        raise ValueError(f"Could not locate before/after matching headers in Body 5 (before={before_idx}, after={after_idx})")

    def parse_char_rows(rows_slice):
        sections = []
        current_sec = None
        for r in rows_slice:
            clean = [c for c in r if c]
            if not clean:
                continue
            if len(clean) == 1 and clean[0][0] in ('Demographics', 'Diagnosis', 'Medication', 'Laboratory'):
                sec_name = clean[0][0]
                current_sec = {'name': sec_name, 'items': []}
                sections.append(current_sec)
                continue
            
            first_text = ' '.join(clean[0])
            if 'cohort' in first_text.lower() or 'mean' in first_text.lower() or 'patient count' in first_text.lower():
                continue
            
            if current_sec is not None:
                c_idx = -1
                for i, c in enumerate(clean):
                    if c == ['1', '2'] or c == ['1', '2', '']:
                        c_idx = i
                        break
                if c_idx != -1 and c_idx + 2 < len(clean):
                    code = clean[c_idx + 1][0] if clean[c_idx + 1] else ''
                    label = clean[c_idx + 2][0] if clean[c_idx + 2] else ''
                    vals = clean[c_idx + 3:]
                    current_sec['items'].append({
                        'code': code,
                        'label': label,
                        'vals': vals,
                    })
                elif len(clean) >= 3 and clean[0] == ['1', '2']:
                    label = clean[1][0]
                    vals = clean[2:]
                    current_sec['items'].append({
                        'code': '',
                        'label': label,
                        'vals': vals,
                    })
        return sections

    before_sections = parse_char_rows(psm_rows[before_idx:after_idx])
    after_sections = parse_char_rows(psm_rows[after_idx:])

    aligned_sections = []
    for b_sec, a_sec in zip(before_sections, after_sections):
        sec_name = b_sec['name']
        items = []
        for b_item, a_item in zip(b_sec['items'], a_sec['items']):
            code = b_item['code']
            label = b_item['label']
            b_vals = b_item['vals']
            a_vals = a_item['vals']
            
            def parse_val_cells(v_cells):
                p_val = '-'
                asd_val = '-'
                if len(v_cells) >= 2:
                    p_val = v_cells[-2][0] if v_cells[-2] else '-'
                    asd_val = v_cells[-1][0] if v_cells[-1] else '-'
                
                if len(v_cells) >= 4 and any('+/-' in x for x in v_cells[0]):
                    m_sd = v_cells[0]
                    c1_str = m_sd[0] if len(m_sd) > 0 else '-'
                    c2_str = m_sd[1] if len(m_sd) > 1 else '-'
                    return {
                        'is_continuous': True,
                        'c1_str': c1_str,
                        'c2_str': c2_str,
                        'p': p_val,
                        'asd': asd_val,
                        'c1_n': None,
                        'c2_n': None,
                    }
                else:
                    counts = []
                    pcts = []
                    for c in v_cells[:-2]:
                        if any('%' in x for x in c):
                            pcts = c
                        elif any(x.replace(',', '').isdigit() for x in c):
                            counts = c
                    
                    c1_n = int(counts[0].replace(',', '')) if len(counts) > 0 and counts[0].replace(',', '').isdigit() else 0
                    c2_n = int(counts[1].replace(',', '')) if len(counts) > 1 and counts[1].replace(',', '').isdigit() else 0
                    c1_pct = pcts[0] if len(pcts) > 0 else '0%'
                    c2_pct = pcts[1] if len(pcts) > 1 else '0%'
                    
                    c1_str = f"{c1_pct} ({c1_n:,})"
                    c2_str = f"{c2_pct} ({c2_n:,})"
                    return {
                        'is_continuous': False,
                        'c1_str': c1_str,
                        'c2_str': c2_str,
                        'c1_n': c1_n,
                        'c2_n': c2_n,
                        'c1_pct': c1_pct,
                        'c2_pct': c2_pct,
                        'p': p_val,
                        'asd': asd_val,
                    }

            b_parsed = parse_val_cells(b_vals)
            a_parsed = parse_val_cells(a_vals)
            
            items.append({
                'code': code,
                'label': label,
                'before': b_parsed,
                'after': a_parsed,
            })
        aligned_sections.append({'name': sec_name, 'items': items})
        
    data['table1_sections'] = aligned_sections

    # 4. Table 2 Outcomes (Body 8)
    b8 = bodies[8]
    b8_tbls = b8.findall('.//w:tbl', NS)
    if not b8_tbls:
        raise ValueError("No table found in Body 8 (Outcomes)")
    tbl_outcomes = b8_tbls[0]
    out_rows = []
    for tr in tbl_outcomes.findall('.//w:tr', NS):
        row_cells = [_cell_lines(tc) for tc in tr.findall('./w:tc', NS)]
        clean = [c for c in row_cells if c]
        out_rows.append(clean)

    outcome_blocks = []
    current_out = None
    for idx, r in enumerate(out_rows):
        if len(r) == 1 and len(r[0]) == 1:
            txt = r[0][0]
            if re.match(r'^\d+\s+[A-Za-z]', txt):
                name = re.sub(r'^\d+\s+', '', txt).strip()
                current_out = {'name': name, 'rows': []}
                outcome_blocks.append(current_out)
                continue
        if current_out is not None:
            current_out['rows'].append(r)

    parsed_outcomes = []
    for ob in outcome_blocks:
        name = ob['name']
        rows = ob['rows']
        
        c1_risk_n = 0
        c1_risk_pct = 0.0
        c2_risk_n = 0
        c2_risk_pct = 0.0
        c1_km_surv = 0.0
        c2_km_surv = 0.0
        logrank_p = '-'
        hr_val = '-'
        hr_ci = '-'
        hr_lo = '-'
        hr_hi = '-'
        
        sub_mode = None
        for r in rows:
            flat = [' '.join(c) for c in r]
            flat_str = ' '.join(flat).lower()
            if 'risk analysis' in flat_str:
                sub_mode = 'risk'
                continue
            elif 'kaplan' in flat_str or 'meier' in flat_str:
                sub_mode = 'km'
                continue
            
            if sub_mode == 'risk':
                if len(flat) >= 5 and flat[0] == '1':
                    c1_risk_n = int(flat[3].replace(',', ''))
                    try:
                        c1_risk_pct = float(flat[4]) * 100.0
                    except ValueError:
                        c1_risk_pct = 0.0
                elif len(flat) >= 5 and flat[0] == '2':
                    c2_risk_n = int(flat[3].replace(',', ''))
                    try:
                        c2_risk_pct = float(flat[4]) * 100.0
                    except ValueError:
                        c2_risk_pct = 0.0
            elif sub_mode == 'km':
                if len(flat) >= 6 and flat[0] == '1' and '%' in flat[5]:
                    c1_km_surv = float(flat[5].replace('%', ''))
                elif len(flat) >= 6 and flat[0] == '2' and '%' in flat[5]:
                    c2_km_surv = float(flat[5].replace('%', ''))
            
            if 'log-rank' in flat_str:
                if len(flat) >= 4:
                    logrank_p = flat[3]
            elif 'hazard ratio and proportionality' in flat_str or ('hazard ratio' in flat_str and len(flat) >= 3 and flat[0] != 'Hazard Ratio'):
                if len(flat) >= 3:
                    hr_val = flat[1]
                    hr_ci = flat[2]
                    m_ci = re.search(r'\(([\d.]+),\s*([\d.]+)\)', hr_ci)
                    if m_ci:
                        hr_lo = m_ci.group(1)
                        hr_hi = m_ci.group(2)

        parsed_outcomes.append({
            'name': name,
            'c1_risk_n': c1_risk_n,
            'c1_risk_pct': c1_risk_pct,
            'c2_risk_n': c2_risk_n,
            'c2_risk_pct': c2_risk_pct,
            'c1_km_surv': c1_km_surv,
            'c2_km_surv': c2_km_surv,
            'c1_event_rate': round(100.0 - c1_km_surv, 2),
            'c2_event_rate': round(100.0 - c2_km_surv, 2),
            'logrank_p': logrank_p,
            'hr': hr_val,
            'hr_ci': hr_ci,
            'hr_lo': hr_lo,
            'hr_hi': hr_hi,
        })
    data['table2_outcomes'] = parsed_outcomes

    # 5. Appendices A, B, C text & code universe
    b9_text = _body_text(bodies[9])
    b10_text = _body_text(bodies[10])
    b11_text = _body_text(bodies[11])
    data['appendix_a_text'] = b9_text
    data['appendix_b_text'] = b10_text
    data['appendix_c_text'] = b11_text

    all_text = '\n'.join([b1_text, b3_text, _body_text(bodies[5]), b9_text, b10_text, b11_text])
    codes_universe = set()
    for m in re.finditer(r'\bUMLS:(ICD10CM|ICD10PCS|CPT|HCPCS):([A-Za-z0-9_.-]+)', all_text):
        codes_universe.add((m.group(1), m.group(2).rstrip('.,;:)')))
    for m in re.finditer(r'\bNLM:RXNORM:([0-9]+)', all_text):
        codes_universe.add(('RXNORM', m.group(1)))
    for m in re.finditer(r'\bTNX:([0-9]+)', all_text):
        codes_universe.add(('TNX', m.group(1)))

    data['codes_universe'] = codes_universe
    return data
